from typing import Protocol
from uuid import UUID

from app.domain.events import DomainEvent
from app.domain.enums import SubmissionStatus
from app.schemas.auth import RefreshTokenCreate, RefreshTokenRecord, User, UserCreate
from app.schemas.core import (
    Batch,
    BatchCreate,
    Evaluation,
    EvaluationCreate,
    MentorReview,
    MentorReviewCreate,
    Organization,
    OrganizationCreate,
    Project,
    ProjectCreate,
    Student,
    StudentCreate,
    Submission,
    SubmissionCreate,
    Task,
    TaskCreate,
)


class OrganizationRepository(Protocol):
    def create(self, payload: OrganizationCreate) -> Organization: ...


class BatchRepository(Protocol):
    def create(self, payload: BatchCreate) -> Batch: ...


class StudentRepository(Protocol):
    def create(self, payload: StudentCreate) -> Student: ...
    def get(self, student_id: UUID) -> Student | None: ...
    def get_by_email(self, email: str, organization_id: UUID | None = None) -> Student | None: ...
    def list_for_org(self, org_id: UUID) -> list[Student]: ...


class ProjectRepository(Protocol):
    def create(self, payload: ProjectCreate) -> Project: ...
    def get(self, project_id: UUID) -> Project | None: ...


class TaskRepository(Protocol):
    def create(self, payload: TaskCreate) -> Task: ...
    def get(self, task_id: UUID) -> Task | None: ...
    def list_student_ids_for_batch(self, batch_id: UUID) -> set[UUID]: ...
    def list_for_student(self, student_id: UUID) -> list[Task]: ...


class SubmissionRepository(Protocol):
    def create(self, payload: SubmissionCreate) -> Submission: ...
    def get(self, submission_id: UUID) -> Submission | None: ...
    def update_status(self, submission_id: UUID, new_status: SubmissionStatus) -> None: ...
    def list_for_batch(self, batch_id: UUID) -> list[Submission]: ...
    def list_for_student(self, student_id: UUID) -> list[Submission]: ...


class EvaluationRepository(Protocol):
    def create(self, payload: EvaluationCreate) -> Evaluation: ...
    def get(self, evaluation_id: UUID) -> Evaluation | None: ...
    def list_for_submission(self, submission_id: UUID) -> list[Evaluation]: ...


class MentorReviewRepository(Protocol):
    def create(self, payload: MentorReviewCreate) -> MentorReview: ...


class EventStore(Protocol):
    def append(self, event: DomainEvent) -> DomainEvent: ...
    def list_by_aggregate(self, aggregate_id: UUID) -> list[DomainEvent]: ...


# Async protocols — used by SqlAlchemyUnitOfWork and AsyncDailyLoopService


class AsyncOrganizationRepository(Protocol):
    async def create(self, payload: OrganizationCreate) -> Organization: ...


class AsyncBatchRepository(Protocol):
    async def create(self, payload: BatchCreate) -> Batch: ...
    async def list_for_org(self, org_id: UUID) -> list[Batch]: ...


class AsyncStudentRepository(Protocol):
    async def create(self, payload: StudentCreate) -> Student: ...
    async def get(self, student_id: UUID) -> Student | None: ...
    async def get_by_email(self, email: str, organization_id: UUID | None = None) -> Student | None: ...
    async def list_for_org(self, org_id: UUID) -> list[Student]: ...


class AsyncProjectRepository(Protocol):
    async def create(self, payload: ProjectCreate) -> Project: ...
    async def get(self, project_id: UUID) -> Project | None: ...


class AsyncTaskRepository(Protocol):
    async def create(self, payload: TaskCreate) -> Task: ...
    async def get(self, task_id: UUID) -> Task | None: ...
    async def list_student_ids_for_batch(self, batch_id: UUID) -> set[UUID]: ...
    async def list_for_student(self, student_id: UUID) -> list[Task]: ...


class AsyncSubmissionRepository(Protocol):
    async def create(self, payload: SubmissionCreate) -> Submission: ...
    async def get(self, submission_id: UUID) -> Submission | None: ...
    async def update_status(self, submission_id: UUID, new_status: SubmissionStatus) -> None: ...
    async def list_for_batch(self, batch_id: UUID) -> list[Submission]: ...
    async def list_for_student(self, student_id: UUID) -> list[Submission]: ...


class AsyncEvaluationRepository(Protocol):
    async def create(self, payload: EvaluationCreate) -> Evaluation: ...
    async def get(self, evaluation_id: UUID) -> Evaluation | None: ...
    async def list_for_submission(self, submission_id: UUID) -> list[Evaluation]: ...


class AsyncMentorReviewRepository(Protocol):
    async def create(self, payload: MentorReviewCreate) -> MentorReview: ...


class AsyncEventStore(Protocol):
    async def append(self, event: DomainEvent) -> DomainEvent: ...
    async def list_by_aggregate(self, aggregate_id: UUID) -> list[DomainEvent]: ...


class UserRepository(Protocol):
    def create(self, payload: UserCreate) -> User: ...
    def get_by_id(self, user_id: UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def update_password(self, user_id: UUID, new_hashed_password: str) -> None: ...


class AsyncUserRepository(Protocol):
    async def create(self, payload: UserCreate) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def update_password(self, user_id: UUID, new_hashed_password: str) -> None: ...


class AsyncRefreshTokenRepository(Protocol):
    async def create(self, payload: RefreshTokenCreate) -> RefreshTokenRecord: ...
    async def get_by_hash(self, token_hash: str) -> RefreshTokenRecord | None: ...
    async def mark_used(self, token_id: UUID) -> None: ...
    async def revoke(self, token_id: UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...
